# Generated by Django 5.0.6 on 2024-06-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_hackathon_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hackathon_participant',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
